### ISSUE TITLE
Space in the end creates a problem [Mass Edit]

### ISSUE THREAD

**Issue by humam2104** [vawser/Smithbox#105]
There's an issue in the program where it gives an error when there's space after the line typed.
![image](https://github.com/user-attachments/assets/c69cd6ec-3199-4a3a-846f-b2710cd1dbb8)
Here, you can see it works fine
![image](https://github.com/user-attachments/assets/3fbbefc5-cdd8-4e1f-a906-48d52264a770)
I was confused what the problem was, especially because dividing created a problem in the program like I previously reported.

**Comment by vawser** [comment]
Fixed in the next release.
