### ISSUE TITLE
Merge regulation.bin without CSV file

### ISSUE THREAD

**Issue by xDerApfelx** [vawser/Smithbox#107]
I am using Smithbox for Elden ring. But the problem is a lot of mods I want dont have a cvs file to download. There is just the regulation.bin file. Is there any way to merge the orginal regulation.bin file from Eldenring with the new bin files from diffrent mods without csv??

I hope you can help me.

**Comment by vawser** [comment]
Yes, if you create a new project and save in the Param Editor, it will save with the vanilla regulation. You can then use the "Merge Params" action to target the regulation from the mod you want to merge into the vanilla regulation, and click the button. You can then repeat this process for each mod you want to merge in.
