### ISSUE TITLE
[1.0.19 Error] I need help

### ISSUE THREAD

**Issue by GGBE123** [vawser/Smithbox#110]
How do i resolve this? I extracted/unpacked the game (Elden Ring) using UXM, on a previous version of this tool it worked fine, this crash never happened, now that i used this version (1.0.19) it always crashes and gives the same error. I would like to go back to the old version of this tool but opening my project and importing row names apparently made it so the old version of this tool unable to read the regulation bin XD, now I'm stuck. The only way of using this tool now is to remove the files made by unpacking the game to a different folder that isn't the game folder. How would i go about fixing this?
![Screenshot 2024-08-24 143652](https://github.com/user-attachments/assets/39e0c821-ac66-4462-9de0-8744c529c7f2)

**Comment by vawser** [comment]
Looks like it is not reading the map files correctly.

**Comment by GGBE123** [comment]
> Looks like it is not reading the map files correctly.

How do i fix this :(, unpack the game again?

**Comment by vawser** [comment]
It appeared to be an issue with the Map Query data bank where it would try and load map files without valid paths. I've added a fix for the next release.
