### ISSUE TITLE
1.0.19 reports an error as soon as it is opened

### ISSUE THREAD

**Issue by iforgiveu** [vawser/Smithbox#111]

**Comment by iforgiveu** [comment]
![屏幕截图 2024-08-24 183143](https://github.com/user-attachments/assets/62fb200f-ea2f-47ee-a005-b6333c0e68ed)

**Comment by iforgiveu** [comment]
Now it is found that it is caused by the TAE of loading the asset, and the error will not be reported when the relevant settings are turned off. Why does the TAE of the asset load report an error?

**Comment by vawser** [comment]
Looks like an issue with the filename handling. Strange though because by default the object/asset TAEs are not loaded. If you delete the AppData/Local/Smithbox folder, that will reset the settings and should let you load Smithbox.
