### ISSUE TITLE
Grammatically confused

### ISSUE THREAD

**Issue by ramonsantana** [vawser/Smithbox#113]
One Settings/System the Formats check box says Ignore Asserts and tooltips. Is the word supposed to be Ignore Asserts or Assets?

**Comment by vawser** [comment]
It is "Ignore Asserts". It is an option to allow users to bypass intentionally 'corrupted' files.

Asserts are used in SoulsFormats when reading data to ensure it is valid, however some people corrupt files by placing junk data within sections that have asserts, causing SoulsFormats to fail to read the data. SoulsFormats is stricter than the game(s), so the corrupted file still works, but cannot be read.
