### ISSUE TITLE
Font and Language issue

### ISSUE THREAD

**Issue by Nazodec** [vawser/Smithbox#120]
Before when using version 1.0.15.1 all items were in english but in every subsequent update I have a strange font that isn't even a real language it seems.
Also when using version 1.0.20 the Print screen function on my pc doesn't work.
I've attached images, sorry about the poor quality of the image.
I've opened them both simultaneously and also tried deleting the previous version before running the new one and that didn't fix the issue either.
![WhatsApp Image 2024-09-14 at 00 15 14_887d14df](https://github.com/user-attachments/assets/b9c8212c-22e3-4a6c-a46f-ac432ca5f680)
![Screenshot 2024-09-14 001038](https://github.com/user-attachments/assets/e4127ea7-0667-40b8-b455-3c6850825efb)

**Comment by Nazodec** [comment]
Solved by basically blindly navigating the settings until the fonts settings wee fond.for some reason it was solved by changing the non english font instead of the english font.

**Comment by RAZORTAIL2023** [comment]
I meet this issue too when I use version 1.0.23，I handle it via change file "Smithbox_Interface.json" in AppData/Local/Smithbox.
Just rewrite the line  "SelectedThemeName": "Dark", to  "SelectedThemeName": "Light", ..

**Comment by maxiride** [comment]
> I meet this issue too when I use version 1.0.23，I handle it via change file "Smithbox_Interface.json" in AppData/Local/Smithbox. Just rewrite the line "SelectedThemeName": "Dark", to "SelectedThemeName": "Light", ..

Changing the theme to light did not resolve the issue for me. Furthermore the JSON configuration files do not seem to have a language option.
I still see the jibberish like the screenshot in the first post.




> Solved by basically blindly navigating the settings until the fonts settings were found, for some reason it was solved by changing the non english font instead of the english font.

Could you please make a step by step video or series of screenshots? Being the first time using the tool I have no clue on where to go.

**Comment by maxiride** [comment]
For anyone coming here in the feature I solved it.

On 1.0.24 I configured the Roboto Font to `System_Other_Font` too.

snippet that made the UI load correctly.
```json
  "System_English_Font": "Assets\\Fonts\\RobotoMono-Light.ttf",
  "System_Other_Font": "Assets\\Fonts\\RobotoMono-Light.ttf",
```
