### ISSUE TITLE
Dark Souls 1 Remastered project crashes at startup

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#123]
Shows these error dialog boxes when opening a new or existing project -

![image](https://github.com/user-attachments/assets/ebdf6419-97b6-4e74-8e93-2fd7781fc296)
![image](https://github.com/user-attachments/assets/807249a2-3c63-4a6d-aa32-7a135a7e345c)

Used to work fine before.

**Comment by vawser** [comment]
Looks to be linked to the WIP ESD Editor. I'll disable the feature flag since it shouldn't have been enabled for a release.
