### ISSUE TITLE
Editing Graphics Config params no longer possible ? (Sekiro)

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#126]
Hi,

in older versions of Smithbox it allowed me to edit graphics config params (such as shadowquality, etc) from Param Editor. This was quite convenient and handy.

However, this button / checkbox no longer seems to show up with a newly created project for Sekiro. Did it get removed or is this some kind of oversight?

**Comment by vawser** [comment]
Looks to be an oversight, I'll fix it for the next release.
