### ISSUE TITLE
(Model Editor) Can't save mappieces in Dark Souls Remastered

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#128]
For whatever reason, objects/parts/characters can be edited, but not mappieces. Ctrl+S does nothing.

**Comment by vawser** [comment]
The save functionality hasn't been added for it yet. I'll see about adding it in.

**Comment by vawser** [comment]
Fixed for next release.

**Comment by LibretroAdmin** [comment]
Since the latest version doesn't seem to have reliable mappiece viewing/editing at all anymore (see https://github.com/vawser/Smithbox/issues/298), I tried going back to an earlier version (2025-01-22). Unfortunately, saving mappieces doesn't work properly there either.

For example,

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/9d782327-aa61-43e7-94e0-289c60e9971f" />

I have 'm0030B2A10' open from Firelink Shrine. I remove the two facesets so that only Faceset 0 remains. I press Ctrl+S to save it. It says 'Saved FLVer file'. I then open 'm0000B2A10'. Then I open 'm0030B2A10' and for whatever reason I see the two facesets again that I removed before and were SUPPOSED to have been saved. Not really sure what is going on here (but as said before, mappiece loading doesn't seem to work at all anymore in the latest version, so that is the first issue to be fixed before we can establish if mappiece editing works at all in the most recent master)

**Comment by LibretroAdmin** [comment]
EDIT/UPDATE: OK, I figured out now that when you save the file with Ctrl+S in the Asset Browser, it will only save the FLVER file, instead of immediately putting it into a DCX file. So when Smithbox tries to read the file again, it reads the old DCX file instead from the project directory instead of the FLVER file that was just saved. So I need to take the FLVER file and do witchybnd on it to turn it into DCX I guess manually
