### ISSUE TITLE
(Map Editor) (Bloodborne) Cannot open any model

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#132]
When I try to open a mappiece or Char in a Bloodborne project with the latest source I get a crash

![image](https://github.com/user-attachments/assets/26b027f1-e221-4d0c-a2ad-b117e38127d0)

Objects and Parts CAN be opened though.

![image](https://github.com/user-attachments/assets/e2a07f5e-9279-473f-a9b5-79a4fc26ca93)

So it only doesn't work for Mappieces and Chars.

**Comment by LibretroAdmin** [comment]
Hmm, sometimes I CAN open chr models though. So it's weird.

![image](https://github.com/user-attachments/assets/649eafd3-ef0c-4be5-b403-43c108cc97be)

**Comment by vawser** [comment]
Fixed for the next release. The BB structure wasn't being handled correctly, so it was trying to load a direct FLVER as a BND.

**Comment by LibretroAdmin** [comment]
Awesome, thanks for all your fast commits!
