### ISSUE TITLE
(Bloodborne) (Model Editor) Cannot save mappieces

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#136]
When trying to save mappieces, it will show an error like this:

Container path does not exist: path-to-file:\dvdroot_ps4\map\m21_00_00_00\m21_00_00_00\m21_00_00_00_000010.mapbnd.dcx

![image](https://github.com/user-attachments/assets/a28b5e9e-dc8c-4022-a9d5-a8e1cad63adb)

**Comment by vawser** [comment]
Fixed for next release.

**Comment by LibretroAdmin** [comment]
Amazing work once again!
