### ISSUE TITLE
(Model Editor - DS2 SOTFS) Crash when trying to load any model/mappiece/object/part

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#138]
As the description says. Trying to load any object for Dark Souls 2: Scholar of the First Sin in Model Editor will just result in a crash.

**Comment by vawser** [comment]
Interesting, seems to be a regression. I'll try and get this fixed, although the crash doesn't make it obvious what the issue is annoyingly.

**Comment by vawser** [comment]
Fixed for next release.
