### ISSUE TITLE
(Model Editor - BB/DS2 - possibly other games) It says it saves a mappiece/character/object with changes but it actually doesn't

### ISSUE THREAD

**Issue by LibretroAdmin** [vawser/Smithbox#140]
This seems to be a recent regression from today. It no longer properly saves a mappiece that has been edited.

Let's say I make some changes to Meshes, like removing a faceset or modifying a parameter like 'Unk06'. I make the changes, I press Ctrl-S or select Save, then I go to another model and then I go back to this mappiece to see if any of my changes have been saved. It turns out it didn't and everything is back to the original values. 

The log message doesn't really tell us anything about what is going wrong either:

Saved model container  BND file at \insertpathhere\Bloodborne\parts\am_a_0009.partsbnd.dcx

**Comment by LibretroAdmin** [comment]
It isn't just Bloodborne either, Dark Souls 2 doesn't save either. Neither characters, mappieces or objects save when making edits.

Seems like a major regression

**Comment by vawser** [comment]
Oops, made a bad assumption about how memory-mapped files work. Fixed for all but the DS2 map pieces.
