### ISSUE TITLE
Crash when using the Time Act Editor's Property Search

### ISSUE THREAD

**Issue by Cat656** [vawser/Smithbox#142]
I'm using the Property search to search through Event Values, but whenever I click on one of the results, Smithbox crashes. Crash log attached. This crash is repeatable and happens even when I try different searches.

[Log 2024-10-11--19-03-03.txt](https://github.com/user-attachments/files/17348447/Log.2024-10-11--19-03-03.txt)

**Comment by vawser** [comment]
Should be fixed for next release.
