### ISSUE TITLE
crashing everytime i try to create a new project

### ISSUE THREAD

**Issue by DeathsTrial** [vawser/Smithbox#143]
everytime i hit create a new project i do everything im supposed to do then when i hit create it gives me a error and crashes along with that it corrupts my file

**Comment by Ryusennin** [comment]
I have the same crash issue since ER 1.16 when trying to update my "No Ambient Music" mod.

Surely there's no need to unpack the whole game just to edit the regulation file?

> Smithbox - Version 1.0.22
> 
> Could not find a part of the path 'D:\Games\Steam\steamapps\common\ELDEN RING\Game\msg'.
> 
>    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String, Boolean )
>    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
>    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String, Boolean, EnumerationOptions )
>    at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1, Boolean)
>    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String, FindTransform, EnumerationOptions, Boolean)
>    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String, FindTransform , EnumerationOptions )
>    at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String, String, EnumerationOptions)
>    at System.IO.Directory.InternalEnumeratePaths(String, String, SearchTarget, EnumerationOptions)
>    at System.IO.Directory.GetFileSystemEntries(String, String, EnumerationOptions)
>    at System.IO.Directory.GetFileSystemEntries(String)
>    at StudioCore.Resource.Locators.TextLocator.SearchFolder(String rootPath, String filePattern, Boolean rootOnly) in ./src/StudioCore/Resource/Locators/TextLocator.cs:line 48
>    at StudioCore.Resource.Locators.TextLocator.GetFmgContainers(Boolean rootOnly) in ./src/StudioCore/Resource/Locators/TextLocator.cs:line 23
>    at StudioCore.Editors.TextEditor.TextBank.<>c.<LoadTextFiles>b__11_0() in ./src/StudioCore/Editors/TextEditor/Data/TextBank.cs:line 53
>    at StudioCore.Editor.TaskManager.LiveTask.<CreateTask>b__15_0() in ./src/StudioCore/Editor/TaskManager.cs:line 187
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )

**Comment by vawser** [comment]
Sorry my bad, I rewrote the Text Editor internals, but I forgot to account for the text folder not being there, so the Text Locator is throwing an error if the msg folder isn't unpacked. I'll fix it for the proper release/next artifact build.
