### ISSUE TITLE
Text editor cant read Georgian font

### ISSUE THREAD

**Issue by Giorma1** [vawser/Smithbox#155]
is there any way to make the Smithbox read Georgian font? it's just writing "????????" instead of "მონაცემი", I have tried to add non-English font from the setting but it did not work. all these "?" are Georgian letters, I have written them by unpacking the MenuText file in msg and writing them.

![Screenshot_1](https://github.com/user-attachments/assets/d5a0abec-90d1-413b-a867-1a5cbf0d85ef)

**Comment by vawser** [comment]
This is a limitation of ImGui I believe, adding support for more complex alphabets isn't trivial and it isn't a priority I'm afraid.

**Comment by Giorma1** [comment]
Ok, no problem thanks for your work 😉
