### ISSUE TITLE
IME Support

### ISSUE THREAD

**Issue by TheFBplus** [vawser/Smithbox#157]
When using input methods such as Chinese or Japanese, the native IME UI is not displayed.Is there any plan to add IME support?

**Comment by vawser** [comment]
Support for IME is not planned.

**Comment by TheFBplus** [comment]
Thanks for the reply.
But I searched and found that to enable IME support, you only need to upgrade the SDL2 library and set the SDL_HINT_IME_SHOW_UI of the SDL2 library to 1:
[SDL_HINT_IME_SHOW_UI](https://wiki.libsdl.org/SDL2/SDL_HINT_IME_SHOW_UI)
[SDL2Fix](https://github.com/libsdl-org/SDL/commit/4c7db129df3f6d56a809826a6fa76375dca422f6
)
This is much more convenient for non-English users.
