### ISSUE TITLE
FMG exporting and importing adds additional linebreaks to all IDs

### ISSUE THREAD

**Issue by dweetacular** [vawser/Smithbox#32]
Exporting and re-importing modified text adds an extra linebreak to the end of each ID's text.
![image](https://github.com/vawser/Smithbox/assets/80144315/1a3434d6-9efa-4626-bf8b-8cb75a0688f6)
![image](https://github.com/vawser/Smithbox/assets/80144315/fe061920-270e-483a-b1ac-8b702d9c75b5)

If you have text that already has linebreaks, it seems to double them up in-game despite appearing correctly in Smithbox.
![image](https://github.com/vawser/Smithbox/assets/80144315/e2f97f13-3cc5-4f03-b00a-84b50e0eb713)
![image](https://github.com/vawser/Smithbox/assets/80144315/13d93111-2138-4406-baf1-7ae0649342e9)
![image](https://github.com/vawser/Smithbox/assets/80144315/df58d8db-2d8c-489f-9658-8525c3da3bcc)
Pressing backspace once on these doubled linebreaks appears to do nothing in Smithbox but removes the second linebreak in-game. Backspacing twice correctly removes the entire linebreak as you would expect.

If it makes any difference, I was exporting these modified text IDs from json text files while updating old mods.

Edit:
It also appears to add an invisible linebreak to the end of any lines that come before a linebreak.

**Comment by vawser** [comment]
Fixed in 1.0.17
