### ISSUE TITLE
Constant Crashing When Loading Project due to Missing "item.msgbnd.dcx" File

### ISSUE THREAD

**Issue by john7200** [vawser/Smithbox#33]
Greetings,

Smithbox v1.0.14.3 is constantly crashing when loading recent projects.
The crashlog is as follow:

[Log 2024-7-03--17-36-37.txt](https://github.com/user-attachments/files/16081254/Log.2024-7-03--17-36-37.txt)

If I'm not mistaken, the file "item.msgbnd.dcx" is one of the Elden Ring assets that is packed within the game files and must be extracted first. I'm using the "Low Requirement" version of Smithbox since I have neither intention nor interest in modding any of the game assets. I only use it for modifying or increasing graphics/visual fidelity in regulation.bin file.

The last Smithbox I used, v1.0.14.2, didn't have this issue.

**Comment by vawser** [comment]
Oh sorry, I've found the issue. The next release will fix this and remove the requirement for the msgbnds to be unpacked.
