### ISSUE TITLE
Chinese font issues

### ISSUE THREAD

**Issue by iforgiveu** [vawser/Smithbox#34]
1.Chinese cannot be entered in the software,but yapped etc can
2.Some Chinese will inexplicably become question marks。
such as:
基？教程。
你大？？

**Comment by mirsxh** [comment]
同样遇到了此问题，求解。

**Comment by vawser** [comment]
There is support for a Chinese font, so try using that. If that doesn't fix the issue, then I'm unsure that it will get fixed. Yapped supporting it might be a side-effect of it using WinForms, where Smithbox mostly uses ImGui, which is much more barebones when it comes to this kind of stuff.

**Comment by iforgiveu** [comment]
The font display is worse when I use Chinese than don't use.
When  don't use Chinese, just some words will become question marks, and if I choose to use Chinese, most of the text will become blank.
such as:
normal:(基础教程）
not use:(基？教程）
use: (      教   ）

**Comment by iforgiveu** [comment]
I'm confused as to why imgui would result in this, it's all utf8 which should be compatible, right?

**Comment by vawser** [comment]
Will not fix. Assuming issue is related to ImGui, this is not possible to change.
