### ISSUE TITLE
Missing save option / not working

### ISSUE THREAD

**Issue by StargazerEle** [vawser/Smithbox#38]
Hello! Thank you so much for the tool! I ran into an issue though, the option to save the models seems to be missing in the new update. Even when changing the keybindings to do it that way the project doesnt seem to save. There's no error logs, nothing out of the ordinary, it just doesn't do anything

**Comment by vawser** [comment]
It has been disabled due to an issue with saving causing the FLVER to be corrupted in some way. It will be restored once I go over the Model Editor and fix that issue, but I can't give a timeframe for when that is.

**Comment by StargazerEle** [comment]
Oooh i see, thank you so much for your work! Please take your time!
