### ISSUE TITLE
Game keeps saying my save files are corrupted when I try and load into the game

### ISSUE THREAD

**Issue by Bobby1728** [vawser/Smithbox#39]
I'm trying to make custom summons for Elden ring and every time I finish making one like i would usually do when making summons in dsmapstudio and try opening the game it gives me the main menu screen and then says my save files are corrupted. It only goes back to normal when I get rid of the all the files the change did. Does anyone know how to fix it?

**Comment by vawser** [comment]
It appears that From Software changed how they read the regulation.bin. The DLC introduced a new form of compression usage (ZSTD), and whilst we can decompress it, using it re-compress doesn't work. 

Previously it appeared using the older form of compression worked fine, but patch 1.12.4 has broken this, causing the "Save Data is Corrupted" message whenever you save a regulation.bin in Smithbox.

**Comment by Bobby1728** [comment]
oh thank you for telling me I was really confused on why it wasn't working. I don't really know much about this stuff so Does the game need to fix the issue in later update or does smithbox need to update? no rush tho to update take your time im just wondering

**Comment by vawser** [comment]
Apparently if you use the [AltSaves DLL](https://www.nexusmods.com/eldenring/mods/2651) you will be able to load the regulation.bin, it bypasses the check.

**Comment by Bobby1728** [comment]
thank you

**Comment by Bobby1728** [comment]
but where is that exactly?

**Comment by Bobby1728** [comment]
oh never mind i found it

**Comment by vawser** [comment]
Oh sorry my bad, the issue just seems to be that you need to launch vanilla with your save at least once after a regulation.bin update. I forgot that, so I thought it was related to the param saving in Smithbox
