### ISSUE TITLE
Cannot load save on startup because of duplicate entries (Elden ring, 10.15)

### ISSUE THREAD

**Issue by SlappyP** [vawser/Smithbox#43]
After updating / creating new regulation.bin Elden Ring won't get past the corrupt save message on startup, removing newly added clearcountcorrectParam entries (new set of entries numbered 100 - 107) solved it.

**Comment by vawser** [comment]
If you get the "Save Data is corrupted" message, that means you need to load your save in vanilla first by launching via ModEngine2 but with an empty mod.

Your save stores a version of the regulation.bin, and when a mod's regulation.bin version is higher than the save's stored version, the "Save Data is corrupted" is displayed.
