### ISSUE TITLE
Model editor doesn't show textures

### ISSUE THREAD

**Issue by Nutshe11PD** [vawser/Smithbox#57]
When I load a model using the model editor, I can only see the coloured model, the textures don't show up.
There doesn't seem to be any difference in the "Materials" on the left sidebar.
How can I fix this?
![image](https://github.com/user-attachments/assets/f892a691-2445-4880-9c2f-c1a0ff4b2ccb)

**Comment by vawser** [comment]
You need to tick "Enable model texturing" in the Viewport tab in the Settings.
![image](https://github.com/user-attachments/assets/5567d5ec-dec2-4498-b796-dec9a51f2d01)

**Comment by Nutshe11PD** [comment]
Thank you so much. Never thought I'd miss this.

**Comment by Nutshe11PD** [comment]
> You need to tick "Enable model texturing" in the Viewport tab in the Settings. ![image](https://private-user-images.githubusercontent.com/4229194/348227292-5567d5ec-dec2-4498-b796-dec9a51f2d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODk2NTIsIm5iZiI6MTcyMDc4OTM1MiwicGF0aCI6Ii80MjI5MTk0LzM0ODIyNzI5Mi01NTY3ZDVlYy1kZWMyLTQ0OTgtYjc5Ni1kZWM5YTUxZjJkMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMTMwMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY4OGUxOGNjYzA1ZmQyZDk1YWVjMjNjNWVkMzBjYzQ0YmUxYzAzMjFlMjY2YTM5ZjAyMjM0NmUwNjkwNGI5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mgdN323PtbX3nK93hihYoSY6Wtjl2f0Fa1-et2ia9AU)

Thank you so much. Never thought I'd miss this.
