### ISSUE TITLE
Spanish (Spain) and Spanish (Latin America) language options save text data to the wrong folders.

### ISSUE THREAD

**Issue by PositronCannon** [vawser/Smithbox#58]
Basically these 2 options seem to be switched. If you save text with Spanish (Spain) is selected, it saves to msg\spaar, which is the one for Latin America, and viceversa.

I verified this by running the game set to Spanish (Spain) with Smithbox set to the same language, and all text was vanilla. But after selecting the Latam option in Smithbox and making the same changes, the modified strings showed up in game.

**Comment by vawser** [comment]
Will be fixed in the next release.

**Comment by vawser** [comment]
Should be fixed now.
