### ISSUE TITLE
Duplicating Enemy breaks Viewport

### ISSUE THREAD

**Issue by LucySnoozy** [vawser/Smithbox#60]
Whenever I duplicate an enemy with Ctrl+D the Viewport goes very glitchy whenever I move the camera.
![image](https://github.com/user-attachments/assets/3ac479eb-e382-4002-b1ce-31be494aece7)

It usually keeps happening whenever that duplicated enemy is selected. Tried it with other Assets but only seems to happen with Enemies specifically.

**Comment by LucySnoozy** [comment]
To add: Doesn't appear to happen to all enemies but especially happens to Skeletons and Wandering Nobles

**Comment by vawser** [comment]
This is a known bug with the rendering system. You can disable the selection outline in the Viewport settings, that can reduce the occurrence of it. But I don't know enough about the rendering internals to fix this, so it is effectively a "will not fix" issue.
