### ISSUE TITLE
[Original] Command not working

### ISSUE THREAD

**Issue by humam2104** [vawser/Smithbox#63]
![image](https://github.com/user-attachments/assets/352a576f-d0c2-45c8-b249-ef14e8fb0874)
Am I using it wrong? Or is it not working. Modified works fine though
Using 1.0.15
EDIT: 1.0.16.1 produces the same issue

**Comment by vawser** [comment]
!modified should do what you want.

**Comment by humam2104** [comment]
> !modified should do what you want.

Didn't test it out yet, but you would probably want to mention that here:
![image](https://github.com/user-attachments/assets/fe6d4f4a-9826-481e-ba20-dcbfd1e19668)
