### ISSUE TITLE
Bug: Modified List not updating

### ISSUE THREAD

**Issue by humam2104** [vawser/Smithbox#67]
I'm pasting a mass edit for a specific field. When I'm done, the params are not shown in green. Instead they appear in white.

https://github.com/user-attachments/assets/b66affa1-1351-4c08-a37b-5bdb5779a845

**Comment by vawser** [comment]
Did you target the regulation.bin in your game directory? If so, then that is why. Smithbox uses the vanilla regulation.bin to determine what has changed. If you are editing it directly, then Smithbox is comparing it against itself, which will result in nothing appearing as 'modified'
