### ISSUE TITLE
Could not acquire next image from the Vulkan swapchain.

### ISSUE THREAD

**Issue by Blasvicht** [vawser/Smithbox#68]
Have a Titan RTX with latest drivers, and low req version works fine. Have correct c++ and .net versions installed as well. Not sure what is going wrong.
[Log 2024-7-21--21-30-02.txt](https://github.com/user-attachments/files/16327197/Log.2024-7-21--21-30-02.txt)
 Crash log attached.

**Comment by vawser** [comment]
I looked into the issue and it seems like it might be linked to the library that is used to implement Vulkun/Veldrid rendering, if the library doesn't support certain drivers then this error can occur.

Unfortunately, if the deeper than updating the libraries then it is unlikely I will be un-able to fix it, the rendering system is probably the most complex code within the project, and I didn't write it.
