### ISSUE TITLE
Exporting and re-importing text causes crashes

### ISSUE THREAD

**Issue by lugia19** [vawser/Smithbox#69]
Tested on AC6, on a completely clean install. If you export some text, then re-import it (not doing merge, but "All" specifically) the game will crash in different places depending on what file you imported. For example, Characters causes it to crash when entering the Arena.

As far as I can tell, there are two issues with the text exporting/importing process:

1) Extra newlines are added to the text of each entry, as reported in #32 
2) %null% entries completely disappear. I believe _this_ is what causes the crash specifically, as doing "Merge" does not lead to it crashing, as the %null% entries remain.

**Comment by vawser** [comment]
I will look into this. Thanks for reporting it.

**Comment by vawser** [comment]
Both these issues will be fixed in the next release.

**Comment by vawser** [comment]
Fixed in 1.0.17
