### ISSUE TITLE
Elden ring export modded text entries cause crash, export all work ok

### ISSUE THREAD

**Issue by xcloudx12345** [vawser/Smithbox#83]
![Screenshot_17](https://github.com/user-attachments/assets/758b6e6c-2b47-48f5-b1db-0388ff8eecd0)
**crash log**

> Smithbox - Version 1.0.17
> 
> The given key 'TitleWeapons_SOTE' was not present in the dictionary.
> 
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at StudioCore.Editors.TextEditor.FmgExporter.ExportFmgTxt(FMGLanguage lang, Boolean moddedOnly) in ./src/StudioCore/Editors/TextEditor/FmgExporter.cs:line 139
>    at StudioCore.TextEditor.TextEditorScreen.DrawEditorMenu() in ./src/StudioCore/Editors/TextEditor/TextEditorScreen.cs:line 144
>    at StudioCore.Smithbox.Update(Single deltaseconds) in ./src/StudioCore/Smithbox.cs:line 540
>    at StudioCore.Smithbox.Run() in ./src/StudioCore/Smithbox.cs:line 336
>    at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 36

**Comment by vawser** [comment]
Thanks for the report. I've worked out the issue, this will be fixed in the next release.
