### ISSUE TITLE
Param Editor-Elden Ring

### ISSUE THREAD

**Issue by Nooneo69** [vawser/Smithbox#84]
I used UXM to unpack then patch it so I can see the ROWS of the DLC's, however only the equip params were uploaded while others like speffect and bullets are not there. 
I think we need an update or a tip.

**Comment by vawser** [comment]
If you mean the row names, you need to use the "Import Row Name" action (under Tools in the menubar, or found in the tool window) to update the names to the latest ones.

**Comment by Nooneo69** [comment]
Well I did that but the problem is not about the Names of Rows, but no Rows at all related to DLC were detected except of the main game obviously.
