### ISSUE TITLE
1.0.17 crashing when trying to load project

### ISSUE THREAD

**Issue by LucySnoozy** [vawser/Smithbox#85]
See attached crash-log, everytime I try to load my project it crashes and creates no recovery files.
[Log 2024-7-29--14-44-08.txt](https://github.com/user-attachments/files/16413167/Log.2024-7-29--14-44-08.txt)

**Comment by vawser** [comment]
Which game? Try deleting the AppData/Local/Smithbox folder, that will reset the CFG variables. I'm guessing you might have enabled "Use project meta", and since I changed the ColorEdit stuff, those old files will be invalid, causing your error.

**Comment by LucySnoozy** [comment]
Using Elden Ring, deleting that folder fixed the issue indeed.
