### ISSUE TITLE
Ransomware warning with the new update

### ISSUE THREAD

**Issue by FilipVem** [vawser/Smithbox#88]
Yeah as the title says, F-Secure gives me a ranswomware/trojan warning and blocks the application with this new update, I know the source code is out and its most likely safe but im still trusting F-Secure  aswell since i can not understand the code at all xD

**Comment by vawser** [comment]
This is not something I can change really, Anti-Virus software can be overzealous and mark memory-editing code (such as the Hot Reload feature) as random viruses.

**Comment by FilipVem** [comment]
Alr alr, guess ill use it anyways, just gotta remember how to make fsecure
ignore it

Den tis 30 juli 2024 14:33Vawser ***@***.***> skrev:
