### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by TheOnlyMugenMax** [vawser/Smithbox#97]
![imagen_2024-08-09_145054701](https://github.com/user-attachments/assets/c8006bf6-1cb6-4b57-9426-33d7913fa930)
Just... Why?

**Comment by vawser** [comment]
You likely toggled the "Show Pinned Params/Rows/Fields Only" setting on by accident (I made the keybind a bit too easy to accidently press). If you open up the Tool Configuration panel (View -> Tool Configuration), you'll be able to set those three settings back to off under the Pin Group section.

**Comment by TheOnlyMugenMax** [comment]
My god, that was the problem... Thanks!
But why is that option is even there? Why someone would see only the pinned are, well, pinned in top? 
I don't quite understand that

**Comment by vawser** [comment]
It was added so a user can reduce the visual clutter if they are working on a specific set of things. I will admit though the chosen keybinds were a bit too easy to use accidently. They are have been set to unbound by default for the next release, so it shouldn't happen again.

**Comment by TheOnlyMugenMax** [comment]
Yeah, thank you for that in advance 
Much appreciate for the quick response and solve my problem!
